name: "ğŸ Generate Snake"

on:
  schedule:
    - cron: "0 3 * * *"   # Ù‡Ø± Ø±ÙˆØ² Ø³Ø§Ø¹Øª 03:00 UTC (05:30 ØªÙ‡Ø±Ø§Ù† / 05:00 Ø§ÛŒØ±Ø§Ù† Ø¨Ø³ØªÚ¯ÛŒ Ø¨Ù‡ DST)
  workflow_dispatch:       # Ø§Ù…Ú©Ø§Ù† Ø§Ø¬Ø±Ø§ÛŒ Ø¯Ø³ØªÛŒ
  push:
    branches: [ main ]     # Ø´Ø±ÙˆØ¹ Ø§ÙˆÙ„ÛŒÙ‡ Ø¨Ø¹Ø¯ Ø§Ø² Ø§ÙˆÙ„ÛŒÙ† Ú©Ø§Ù…ÛŒØª Ø±ÙˆÛŒ main

permissions:
  contents: write          # Ø§Ø¬Ø§Ø²Ù‡â€ŒÛŒ commit Ø¨Ù‡ Ø±Ø¨Ø§Øª

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Generate snake svgs
        uses: Platane/snk@v3
        with:
          github_user_name: sedaghat-frontdev
          outputs: |
            dist/github-snake.svg
            dist/github-snake-dark.svg?palette=github-dark

      - name: Commit snake to 'output' branch
        uses: EndBug/add-and-commit@v9
        with:
          message: "chore: update contribution snake"
          add: 'dist/*'
          new_branch: output
